spring:
  application:
    name: api-gateway
server:
  port: 7006

zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      serviceId: hello-service
    api-b-url:
      path: /api-b-url/**
      serviceId: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
